### ISSUE TITLE
Error running tool

### ISSUE THREAD

**Issue by binodpanta** [apsdehal/qunit-migrate#10]
I get an error after installing and running

% /home/bpant/local/bin/qunit-migrate test/componenttests.html --no-jscs -w --preset "google"
✖ Error occured while fixing file: test/componenttests.html
Error: Line 1: Unexpected token <
Following files were not converted:
✖ test/componenttests.html

The file exists there, and I also tried with -c "default.json" where default.json was downloaded from the default config json provided

Not sure if this has to do with how my qunit-migrate was installed

% ls -al /home/bpant/local/bin/qunit-migrate
lrwxrwxrwx 1 bpant users 51 Aug  3 10:07 /home/bpant/local/bin/qunit-migrate -> ../lib/node_modules/qunit-migrate/bin/qunit-migrate*

**Comment by binodpanta** [comment]
The file I am converting looks like this 

```
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Cache-Control" content="no-cache" />
    <meta http-equiv="Pragma" content="no-cache" />
    <meta http-equiv="Expires" content="0" />

    <title>Component unit tests</title>
    <link rel="stylesheet" href="/test/tools/javascript/libs/qunit/qunit.css">
</head>

<body>
<!-- The following DIVs are required by the QUnit testing framework -->
<div id="qunit"></div>
<div id="qunit-fixture"></div>

<script src="/test/tools/javascript/libs/qunit/qunit.js"></script>
<script src="/test/tools/javascript/libs/funcunit/jquery.js"></script>
<script src="/test/tools/javascript/libs/funcunit/funcunit.js"></script>

<!-- actual test js -->
<script src="ComponentTests.js"></script>

</body>
</html>

```

**Comment by apsdehal** [comment]
It is supposed to be run on `js` files. Currently, it doesn't automatically extracts script tags from html documents.

**Comment by binodpanta** [comment]
ok thanks, I did not catch that from the doc but perhaps I did not read well!

**Comment by apsdehal** [comment]
Thanks. I will probably update the docs to mention that. Closing this for now. If issue still persists, feel free to reopen.
