### ISSUE TITLE
how to glob files

### ISSUE THREAD

**Issue by danielspaniel** [apsdehal/qunit-migrate#11]
Hi, Glad you made this migration runner, because it is helpful.
Strangely, I can't get globbing to work.

I can run single files no problem though. 

let's say I have tests in => tests/unit/models directory
and there are files in there like user-test.js , etc 

say I am on tests/ directory

if I do:

```
 qunit-migrate './unit/**/*.js'   // get error ( can't find any files )  
 qunit-migrate './unit/models/*.js'   // get error ( can't find any files )  
 qunit-migrate './unit/models/user-test.js'   // works fine ( only does one file thought .. kinda boring ) 
```

I am kinda puzzled cause it seems to easy .. am I missing something?

**Comment by apsdehal** [comment]
Hi @danielspaniel. Thanks for reporting the issue, it was indeed there. I have fixed the issue for now. If you find that the issue still persists, please reopen the issue and I will look into it again. Thanks again.

**Comment by danielspaniel** [comment]
Thanks partner, will give this a try.
