### ISSUE TITLE
Convert asyncTest()/start() to test()/assert.async()/done()

### ISSUE THREAD

**Issue by jzaefferer** [apsdehal/qunit-migrate#4]
asyncTest(), stop() and start() (as used in tests) are deprecated: http://api.qunitjs.com/QUnit.asyncTest/

Noticed this while reviewing https://github.com/jquery/jquery-ui/pull/1577 - but addressing that will affect other projects as well.

**Comment by jzaefferer** [comment]
@apsdehal is this something you could add to your tool?

**Comment by apsdehal** [comment]
Yes, I will do it by this weekend.

**Comment by apsdehal** [comment]
@jzaefferer Working support for this has been added. A more robust and efficient solution would require using JS AST. I have put that on project's timeline.
