### ISSUE TITLE
Can we combine our efforts?

### ISSUE THREAD

**Issue by platinumazure** [apsdehal/qunit-migrate#5]
I'm working on a tool [platinumazure/qunit2-migrator](https://github.com/platinumazure/qunit2-migrator). Is it worth combining our efforts somehow?

**Comment by apsdehal** [comment]
Hi!
Yes, we can. Do you have any ideas?

**Comment by leobalter** [comment]
hey! Is there anything I could help you? I'm probably releasing 2.0 in less than 2 weeks, 1.23.0 might be the last 1.x version (unless we release bug patches)

**Comment by platinumazure** [comment]
Sorry, I've dropped the ball on this, been busy with a few other projects. I need to see what this plugin can do again.

**Comment by platinumazure** [comment]
Okay, I've largely abandoned my project, so I'll check in some README changes on my project linking to this one.
